language: node_js
node_js:
  - '0.12'
sudo: false
install:
  - npm install
script:
  - npm run lint
  - npm run test
after_success:
  - echo done
notifications:
  - webhooks: https://hooks.pubu.im/services/nee6mqnd84qpcwd
